### ISSUE TITLE
Basic Counter Example development

### ISSUE THREAD

**Issue by thruflo** [vaxine-io/examples#1]
As a first step towards working demos, let's take a Phoenix LiveView app, connect it to Antidote using the Ecto adapter and deploy it on our infrastructure.

- [x] #3
- [x] Deployment
  - [x] #4 
  - [x] #7
  - [x] https://github.com/vaxine-io/mesh/issues/6
  - [x] #9
  - [x] #10
  - [x] Website integration - https://github.com/vaxine-io/website/issues/8
- [x] #5 
- [x] #13

**Comment by thruflo** [comment]
@icehaunter suggestion, we could cut out the website integration and visual tidy up to a separate "first demo integrated and live" epic?

**Comment by icehaunter** [comment]
@thruflo I don't now tbh, in my opinion the "visibility" of the demo is a pretty integral part of it as far as its usefulness goes. I am not sure that it makes sense to split an epic, given first part of the epic won't yield anything business-valuable yet

**Comment by thruflo** [comment]
Fwiw I kind of see it the other way but I'm happy to go with however you see it. I'll add a "fine pass on the copy and visuals" issue to the task list above.

**Comment by balegas** [comment]
For me the important thing is that we have visibility about what is in progress. In that sense, if someone else is picking visual aspect of the application we could break down the epic. Also, we don't epics to be very long. 
Having said that, I also understand the perspective that the example is a full package: logic, visuals, deployment. I am happy to be flexible and don't force too much structure here (and therefore just having an issue for the visuals, if it is a short-lived thing is fine).
